@startuml Anwendungskern

interface Promise<T>

package @nestjs/common {
  class "@Injectable" as Injectable
  hide Injectable circle
}

package typeorm {
  class Repository<T>
}

package @nestjs/typeorm {
  class "@InjectRepository" as InjectRepository
  hide InjectRepository circle
}

package student {
  package entity {
    class Student
  }

  package service #DDDDDD {
    class QueryBuilder

    class StudentReadService << control >> <<@Injectable()>> {
      + async findById(id: number): Promise<Student | undefined>
      + async find(suchkriterien?: Record<string, any>): Promise<Student[]>
    }

    StudentReadService o--> "1" QueryBuilder: queryBuilder
    StudentReadService o--> "1" Repository: @InjectRepository repo

    StudentReadService .up.> Injectable
    StudentReadService .up.> InjectRepository

    StudentReadService .up.> Promise
    StudentReadService ..> Student

    QueryBuilder .[hidden].> Repository
    QueryBuilder .[hidden].> Student
  }
}

hide empty members

@enduml
