@startuml Controller-Klasse

interface Promise<T>

package @nestjs/common {
  class "@Controller" as Controller
  hide Controller circle

  class "@Get" as Get
  hide Get circle

  class "@Req" as Req
  hide Req circle

  class "@Res" as Res
  hide Res circle

  class "@Param" as Param
  hide Param circle

  class "@Query" as Query
  hide Query circle

  class "@UseInterceptors" as UseInterceptors
  hide UseInterceptors circle
}

package express {
  class Request
  class Response

  Response .[hidden].> Controller
}

package student {
  package entity #FFFFFF {
    class Student <<entity>>

    Student .[hidden].> Promise
    Student .[hidden].> Request
  }

  package service {
    class StudentReadService << control >>
  }

  package rest #DDDDDD {
    StudentQuery -up-|> Student

    class StudentGetController << control >> << @Controller() >> << @UseInterceptors() >> {
      + @Get() async getById(@Param() id: number, @Req() req: Request, @Headers() version: string, @Res() res: Response): Promise<Response<StudentModel | undefined>>
      + @Get() async get(@Query() query: StudentQuery, @Req() req: Request,  @Res() res: Response): Promise<Response<StudentenModel | undefined>>
    }

    StudentGetController o--> "1" StudentReadService : service

    StudentGetController ..> Controller
    StudentGetController ..> Request
    StudentGetController ..> Response
    StudentGetController ..> Promise
    StudentGetController .up.> StudentModel
    StudentGetController .up.> StudentQuery

    StudentReadService .[hidden].> Request
    StudentReadService .[hidden].> Promise
    Response .right[hidden].> Controller
  }
}

hide empty members

@enduml
